name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ccache git libffi-dev libssl-dev python3-pip python3-setuptools python3-virtualenv unzip wget

    - name: Install Buildozer and Cython
      run: |
        pip install --upgrade pip
        pip install --user buildozer cython==0.29.36

    - name: Build with Buildozer
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        buildozer -v android debug
